version: "3.4"
services:
  consul-server:
    image: hashicorp/consul:1.10.0
    container_name: consul-server
    restart: always
    hostname: service-registry
    volumes:
     - ./consul/server.json:/consul/config/server.json:ro
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent"

  consul-client:
    image: hashicorp/consul:1.10.0
    container_name: consul-client
    restart: always
    volumes:
     - ./consul/client.json:/consul/config/client.json:ro
    networks:
      - consul
    command: "agent"
    
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
        RABBITMQ_ERLANG_COOKIE: guest
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
    networks:
      - consul
    ports:
      - 5672:5672
      - 15672:15672
    hostname: rabbitmq

  
  api-gateway:
    container_name: demo-api-gateway
    depends_on:
        - consul-server
    networks:
      - consul
    build:
      context: .
      dockerfile: apigatewayDockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Docker
    ports: 
      - "5001:80" 

amenity-ordering:
    container_name: amenityordering
    networks:
    build:
      context: .
      dockerfile: amenityorderingDockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Docker
    ports: 
      - "5003:80" 
      
      
networks:
  consul:
    driver: bridge